language: python

os:
  - linux

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install -r requirements.txt

  # Extra dependencies for running tests
  - pip install coverage

script:
  - coverage run -m unittest
